#:schema node_modules/wrangler/config-schema.json
name = "pplab-cron"
main = "src/index.js"
compatibility_date = "2025-03-24"

# Cloudflare Observability & Logs
[observability]
[observability.logs]
enabled = true
invocation_logs = true

# Scheduled events (Cron jobs)
# This runs every day at 21:00 (local UTC+8 / 13:00 UTC)
[triggers]
crons = ["0 13 * * *"]

# Read products.txt as a text module
[[rules]]
type = "Text"
globs = ["**/*.txt"]
fallthrough = true

[[d1_databases]]
binding = "DB" # The binding name available in env.DB
database_name = "pplab-db"
database_id = "4b3eeaa4-7bb8-4ea7-8c36-7c9d20a7f10e"
